import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";

/** `bun syllabi <board> <migration name>`: the board's syllabus files (supabase/syllabi/<board>/<class>/<subject>.json,
 *  the source a person edits) written as one migration of upserts into public.syllabi. Chapter names and section
 *  headings only, no textbook text (D58). */

const Chapter = z.object({
  position: z.number().int().min(1),
  name: z.string().min(1).max(200),
  skills: z.array(z.string().min(1).max(200)).min(1),
});
const Blueprint = z.object({
  marks: z.number().int().positive(),
  durationMinutes: z.number().int().positive(),
  sections: z.array(z.object({ name: z.string().min(1).max(40), questions: z.number().int().positive(), marksEach: z.number().positive() })).min(1),
});
export const SyllabusFile = z
  .object({
    board: z.enum(["cbse", "karnataka", "icse"]),
    classLevel: z.enum(["8", "9", "10"]),
    subject: z.enum(["Mathematics", "Science", "Social Science", "English"]),
    edition: z.string().min(1).max(40),
    source: z.string().min(1),
    chapters: z.array(Chapter).min(1),
    blueprint: Blueprint.nullable(),
  })
  .refine((f) => f.chapters.every((c, i) => c.position === i + 1), { message: "chapters must be numbered 1, 2, 3 in order" });
export type SyllabusFile = z.infer<typeof SyllabusFile>;

const quote = (s: string) => `'${s.replace(/'/g, "''")}'`;
/** Dollar-quoted, so the JSON needs no escaping; a value holding the tag itself is refused. */
const json = (value: unknown) => {
  const text = JSON.stringify(value);
  if (text.includes("$json$")) throw new Error("a syllabus value contains $json$");
  return `$json$${text}$json$::jsonb`;
};

export function renderMigration(files: SyllabusFile[]): string {
  const rows = files.map((f) => {
    const chapters = f.chapters.map(({ position, name, skills }) => ({ position, name, skills }));
    return `  (${quote(f.board)}, ${quote(f.classLevel)}, ${quote(f.subject)}, ${quote(f.edition)}, ${json(chapters)}, ${f.blueprint ? json(f.blueprint) : "null"})`;
  });
  return [
    "-- Generated by `bun syllabi` from supabase/syllabi/<board>/**.json; edit the JSON and generate again, never this file",
    "-- once it has run on the hosted project. Chapter names and section headings only, no textbook text (D58).",
    "insert into public.syllabi (board, class_level, subject, edition, chapters, blueprint) values",
    rows.join(",\n"),
    "on conflict (board, class_level, subject, edition) do update set chapters = excluded.chapters, blueprint = excluded.blueprint;",
    "",
  ].join("\n");
}

/** Every file of a board, in class then subject order; a file whose board or class differs from its folder is refused. */
export function readBoard(root: string, board: string): SyllabusFile[] {
  const out: SyllabusFile[] = [];
  for (const cls of readdirSync(join(root, board))) {
    for (const name of readdirSync(join(root, board, cls)).filter((n) => n.endsWith(".json"))) {
      const parsed = SyllabusFile.parse(JSON.parse(readFileSync(join(root, board, cls, name), "utf8")));
      if (parsed.board !== board || parsed.classLevel !== cls) throw new Error(`${board}/${cls}/${name} names another board or class`);
      out.push(parsed);
    }
  }
  return out.sort((x, y) => Number(x.classLevel) - Number(y.classLevel) || x.subject.localeCompare(y.subject));
}

if (import.meta.main) {
  const [board, name] = process.argv.slice(2);
  if (!board || !name) {
    console.error("usage: bun syllabi <board> <migration name without .sql>");
    process.exit(2);
  }
  const files = readBoard(join(import.meta.dir, "..", "supabase", "syllabi"), board);
  const path = join(import.meta.dir, "..", "supabase", "migrations", `${name}.sql`);
  writeFileSync(path, renderMigration(files));
  console.log(`${files.length} syllabi → ${path}`);
}
