-- V2 (docs/spec-v2.md sections 5, 8 and 9): what the school sent, school marks, the reference syllabi, the V2 message
-- kinds, and the photos bucket. Additive (D26).

create type public.school_item_kind as enum ('exam', 'homework', 'notice', 'holiday');

-- An item is for one student, or for a school's class (school_id and class_level), as the message names it.
create table public.school_items (
  id uuid primary key default gen_random_uuid(),
  centre_id uuid not null references public.centres(id) on delete cascade,
  school_id uuid,
  student_id uuid,
  class_level text check (class_level is null or class_level in ('lkg', 'ukg', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10')),
  kind public.school_item_kind not null,
  subject text check (subject is null or char_length(subject) <= 80),
  date date not null,
  portions text check (portions is null or char_length(portions) <= 2000),
  source_text text check (source_text is null or char_length(source_text) <= 4000),
  photo_path text,
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (centre_id, id),
  foreign key (centre_id, school_id) references public.schools(centre_id, id) on delete set null (school_id),
  foreign key (centre_id, student_id) references public.students(centre_id, id) on delete cascade
);
create trigger school_items_updated before update on public.school_items for each row execute function public.set_updated_at();
create index school_items_date on public.school_items(centre_id, date);

alter table public.artefacts
  add foreign key (centre_id, school_item_id) references public.school_items(centre_id, id) on delete set null (school_item_id);

create table public.marks (
  id uuid primary key default gen_random_uuid(),
  centre_id uuid not null references public.centres(id) on delete cascade,
  student_id uuid not null,
  subject text not null check (char_length(subject) between 1 and 80),
  test text not null check (char_length(test) between 1 and 80),
  date date not null,
  score numeric(6, 2) not null check (score >= 0),
  max numeric(6, 2) not null check (max > 0),
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (score <= max),
  unique (centre_id, id),
  foreign key (centre_id, student_id) references public.students(centre_id, id) on delete cascade
);
create trigger marks_updated before update on public.marks for each row execute function public.set_updated_at();
create index marks_student on public.marks(centre_id, student_id, date);

do $$
declare t text;
begin
  foreach t in array array['school_items', 'marks'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy %I on public.%I for all to authenticated '
                   'using (public.is_member(centre_id)) with check (public.is_member(centre_id))', t || '_member', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;

-- Reference data, not a centre table: written by migrations only (0013 and 0014 are generated by `bun syllabi`); read
-- by signed-in users. Chapters: [{"position": 1, "name": "...", "skills": ["...", "..."]}]: chapter names and section
-- headings only, no textbook text (D58). Blueprint (class 10): the board's marks pattern.
create table public.syllabi (
  id uuid primary key default gen_random_uuid(),
  board text not null check (board in ('cbse', 'icse', 'karnataka')),
  class_level text not null check (class_level in ('8', '9', '10')),
  subject text not null check (char_length(subject) between 1 and 80),
  edition text not null check (char_length(edition) between 1 and 40),
  chapters jsonb not null default '[]'::jsonb check (jsonb_typeof(chapters) = 'array'),
  blueprint jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (board, class_level, subject, edition)
);
create trigger syllabi_updated before update on public.syllabi for each row execute function public.set_updated_at();
alter table public.syllabi enable row level security;
create policy syllabi_read on public.syllabi for select to authenticated using (true);
revoke all on public.syllabi from authenticated;
grant select on public.syllabi to authenticated;

-- A student's chapter copied from the board's list names it (migration 0009 made the column).
alter table public.chapters
  add foreign key (syllabus_id) references public.syllabi(id) on delete set null (syllabus_id);

alter type public.message_kind add value 'note';
alter type public.message_kind add value 'can_do';
alter type public.message_kind add value 'test_tomorrow';
alter type public.message_kind add value 'homework';
alter type public.message_kind add value 'consent';
alter table public.message_log
  add column language text check (language is null or language in ('en', 'hinglish', 'hi', 'kn')),
  add column body text check (body is null or char_length(body) <= 4000);

-- One private bucket for textbook, item and mark photos, under <centre id>/<kind>/<uuid>.jpg; a member reads, writes
-- and deletes under their centre's folder only. A first segment that is not a centre's id reaches nothing.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('photos', 'photos', false, 3145728, array['image/jpeg']) on conflict (id) do nothing;

create function public.photo_centre(p_name text) returns uuid
language sql immutable set search_path = '' as $$
  select case when (storage.foldername(p_name))[1] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
              then ((storage.foldername(p_name))[1])::uuid end
$$;
revoke all on function public.photo_centre(text) from public, anon;
grant execute on function public.photo_centre(text) to authenticated;

create policy photos_member_read on storage.objects for select to authenticated
  using (bucket_id = 'photos' and coalesce(public.is_member(public.photo_centre(name)), false));
create policy photos_member_write on storage.objects for insert to authenticated
  with check (bucket_id = 'photos' and coalesce(public.is_member(public.photo_centre(name)), false));
create policy photos_member_delete on storage.objects for delete to authenticated
  using (bucket_id = 'photos' and coalesce(public.is_member(public.photo_centre(name)), false));
